
# nixpacks.toml

# Specify the backend and frontend directories
[build]
# Define the backend (Node.js)
backend = "backend"

# Define the frontend build process
[[steps]]
# Step for building the backend
name = "Install backend dependencies"
run = "cd backend && npm install"

[[steps]]
# Step for building the frontend
name = "Install frontend dependencies"
run = "cd fontend && npm install && npm run build"

[[steps]]
# Step to copy the built frontend files to the backend directory (so backend can serve them)
name = "Copy frontend build to backend"
run = "cp -r fontend/dist backend/public"

[run]
# Define the command to start the backend
cmd = "cd backend && npm start"
